Document: delpd
Title: Debian delpd Manual
Author: <insert document author here>
Abstract: This manual describes what delpd is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/delpd/delpd.sgml.gz

Format: postscript
Files: /usr/share/doc/delpd/delpd.ps.gz

Format: text
Files: /usr/share/doc/delpd/delpd.text.gz

Format: HTML
Index: /usr/share/doc/delpd/html/index.html
Files: /usr/share/doc/delpd/html/*.html

  
